### ISSUE TITLE
ExportSAC error in WinstonTools 1.3.4

### ISSUE THREAD

**Issue by dlnorgaard** [usgs/winston#82]
Gets following stack trace:

Starting export...
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: gov/usgs/volcanoes/wwsclient/WWSClient
	at gov.usgs.volcanoes.winston.tools.pannel.ExportSACPanel.go(ExportSACPanel.java:156)
	at gov.usgs.volcanoes.winston.tools.WinstonToolsRunnablePanel$1.run(WinstonToolsRunnablePanel.java:19)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: gov.usgs.volcanoes.wwsclient.WWSClient
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

**Comment by tparker-usgs** [comment]
This is the result of a circular dependency. My inclination is to remove the ExportSAC pane from WinstonTools. It's not a good fit for the other server-based tools there. 

Is a GUI ExportSAC needed? If so, it might make more sense to separate WinstonTools from the server and have it stand alone. Let me know what you think.

**Comment by dlnorgaard** [comment]
One of the seismologist was trying to use the GUI version but he is also capable of using the client jar file from command line to export (once he was reminded it existed), so the GUI version probably is not necessary, though nice to have if it worked.
