### ISSUE TITLE
Winston Troubles Windows

### ISSUE THREAD

**Issue by slisowski** [usgs/winston#95]
I'm running on a client's Windows Server 2016
<pre>C:\Earthworm\run\params>java --version
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)</pre>
<pre>
MariaDB [(none)]> select version();
+----------------+
| version()      |
+----------------+
| 10.4.7-MariaDB |
+----------------+
</pre>

ImportEW.bat creates the instruments tables in the wws_root database, but then fails to create channels. 
<pre>
2019-09-02 23:28:55 ERROR - Could not create tables in WWS database.  Are permissions set properly? ({})
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DOUBLE DEFAULT 1E300,  UNIQUE KEY (code)  )' at line 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2536)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:734)
	at gov.usgs.volcanoes.winston.db.WinstonDatabase.createTables(WinstonDatabase.java:210)
	at gov.usgs.volcanoes.winston.db.WinstonDatabase.checkDatabase(WinstonDatabase.java:293)
	at gov.usgs.volcanoes.winston.in.ew.ImportEW.processWinstonConfig(ImportEW.java:329)
	at gov.usgs.volcanoes.winston.in.ew.ImportEW.processConfigFile(ImportEW.java:244)
	at gov.usgs.volcanoes.winston.in.ew.ImportEW.<init>(ImportEW.java:192)
	at gov.usgs.volcanoes.winston.in.ew.ImportEW.main(ImportEW.java:987)
</pre>
If I do this manually, the create command succeeds:
`
CREATE TABLE channels (sid INT PRIMARY KEY AUTO_INCREMENT, iid INT, code VARCHAR(50), st DOUBLE, et DOUBLE,  alias VARCHAR(255), unit VARCHAR(255), linearA DOUBLE DEFAULT 1E300, linearB DOUBLE DEFAULT 1E300, UNIQUE KEY (code) ) ENGINE = MYISAM;`

The channels table is then populated if I run ImportEW again, though iid values are all NULL. 

I then access with Swarm, but it looks like still more tables didn't get created properly, here's WWS log:

<pre>
2019-09-02 11:50:29  INFO - Version: 1.3.7 Built: 20190806-1901
2019-09-02 11:50:29  INFO - config: wws.addr=127.0.0.1.
2019-09-02 11:50:29  INFO - config: wws.port=16023.
2019-09-02 11:50:29  INFO - config: wws.dbConnections=5.
2019-09-02 11:50:29  INFO - Launching WWS. Version: 1.3.7 Built: 20190806-1901
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0 (file:/C:/Earthworm/earthworm_7.10/src/archiving/winston-1.3.7/lib/winston.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-09-02 11:50:29  INFO - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
2019-09-02 11:50:30  INFO - WWS started and listen on /127.0.0.1:16023
Logging level set to "Warn"
Enter ? for console commands.
2019-09-02 11:51:46 ERROR - executeQuery() failed, SQL: SELECT * FROM groupnodes. (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'wws_root.groupnodes' doesn't exist)
2019-09-02 11:51:46 ERROR - : failed on attempt 1
2019-09-02 11:51:46 ERROR - executeQuery() failed, SQL: SELECT * FROM groupnodes. (java.sql.SQLException: No database selected)
2019-09-02 11:51:46 ERROR - : failed on attempt 2
2019-09-02 11:51:46 ERROR - executeQuery() failed, SQL: SELECT * FROM groupnodes. (java.sql.SQLException: No database selected)
2019-09-02 11:51:46 ERROR - : failed on attempt 3
2019-09-02 11:51:46 ERROR - : unsuccessful after 3 attempts.
2019-09-02 11:51:46 ERROR - Could not get groups.
2019-09-02 11:51:46 ERROR - executeQuery() failed, SQL: SELECT sid, nid FROM grouplinks. (java.sql.SQLException: No database selected)
2019-09-02 11:51:46 ERROR - : failed on attempt 1
2019-09-02 11:51:46 ERROR - executeQuery() failed, SQL: SELECT sid, nid FROM grouplinks. (java.sql.SQLException: No database selected)
2019-09-02 11:51:46 ERROR - : failed on attempt 2
2019-09-02 11:51:46 ERROR - executeQuery() failed, SQL: SELECT sid, nid FROM grouplinks. (java.sql.SQLException: No database selected)
2019-09-02 11:51:46 ERROR - : failed on attempt 3
2019-09-02 11:51:46 ERROR - : unsuccessful after 3 attempts.
2019-09-02 11:51:46 ERROR - Could not get channels.
gov.usgs.volcanoes.winston.db.DbException: Cannot execute query
        at gov.usgs.volcanoes.winston.db.WinstonDatabase.executeQuery(WinstonDatabase.java:197)
        at gov.usgs.volcanoes.winston.db.Channels.getChannels(Channels.java:122)
        at gov.usgs.volcanoes.winston.server.GetChannelsConsumer.execute(GetChannelsConsumer.java:24)
        at gov.usgs.volcanoes.winston.server.GetChannelsConsumer.execute(GetChannelsConsumer.java:10)
        at gov.usgs.volcanoes.winston.server.WinstonDatabasePool.doCommand(WinstonDatabasePool.java:46)
        at gov.usgs.volcanoes.winston.server.wws.cmd.GetChannelsCommand.doCommand(GetChannelsCommand.java:51)
        at gov.usgs.volcanoes.winston.server.wws.WwsBaseCommand.respond(WwsBaseCommand.java:49)
        at gov.usgs.volcanoes.winston.server.wws.WwsCommandHandler.channelRead0(WwsCommandHandler.java:59)
        at gov.usgs.volcanoes.winston.server.wws.WwsCommandHandler.channelRead0(WwsCommandHandler.java:29)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:203)
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
        at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:322)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:299)
        at gov.usgs.volcanoes.winston.server.PortUnificationDecoder.switchToWws(PortUnificationDecoder.java:124)
        at gov.usgs.volcanoes.winston.server.PortUnificationDecoder.decode(PortUnificationDecoder.java:105)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:513)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.base/java.lang.Thread.run(Thread.java:835)
</pre>

I set up this same version of Winston 1.3.7 with the same Swarm client 2.8.11 on CentOS previous with success so I think the problem is likely Windows vs. Linux? (not sure if it was the same v. or Maria DB or OpenJDK; I can find out if helpful)

**Comment by slisowski** [comment]
I tried adding all the wws_root tables manually, though I didn't know what to insert into the version table.  I was then able to view the channel list in Swarm, and the helicorder view worked (saw small squiggles). But when I went to click on a waveform in the helicorder view to get detail, I got this error:
<pre>2019-09-03 12:25:35  INFO - Swarm version/date: Version: 2.8.11 Built: 2019-06-03T22:05:48Z
2019-09-03 12:25:54  INFO - current directory: C:\Earthworm\earthworm_7.10\src\display\swarm-2.8.11
2019-09-03 12:25:54  INFO - user.home: C:\Users\earthworm
2019-09-03 12:25:54  INFO - Using configuration file: Swarm.config
2019-09-03 12:25:54  INFO - java.version: 12.0.2
2019-09-03 12:25:54  INFO - maximum heap size: 989.875 MB
2019-09-03 12:25:57  INFO - loading MapPack: mapdata\augustine\MapPack.txt
2019-09-03 12:25:57  INFO - loading MapPack: mapdata\nasa_240m_A1\MapPack.txt
2019-09-03 12:25:57  INFO - loading MapPack: mapdata\nasa_240m_D2\MapPack.txt
2019-09-03 12:25:57  INFO - loading MapPack: mapdata\nasa_2k\MapPack.txt
2019-09-03 12:25:57  INFO - loading MapPack: mapdata\world\MapPack.txt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0 (file:/C:/Earthworm/earthworm_7.10/src/display/swarm-2.8.11/lib/swarm.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-09-03 12:27:15  INFO - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
"ava.lang.NumberFormatException: For input string: "23418
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
        at java.base/java.lang.Integer.parseInt(Integer.java:658)
        at java.base/java.lang.Integer.parseInt(Integer.java:776)
        at gov.usgs.volcanoes.wwsclient.handler.GetWaveHandler.handle(GetWaveHandler.java:50)
        at gov.usgs.volcanoes.wwsclient.handler.WWSClientHandler.channelRead(WWSClientHandler.java:39)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.base/java.lang.Thread.run(Thread.java:835)</pre>

**Comment by tparker-usgs** [comment]
This problem affected all platforms and was fixed with 8acabcd8097bec6197052dc3cc5ccc048702ae4f, which appears in Winston 1.3.13.
